displayName=Confirm Spellbook
author=Endrit
description=Confirm your spellbook after bank withdrawals and check for missing thrall supplies
tags=confirm,spellbook,ancient,ancients,ancient magicks,standard,lunar,arceuus,thrall,thralls,book of the dead,rune pouch,runes,magic,reminder,warning,loadout,endrit
plugins=com.confirmspellbook.ConfirmSpellbookPlugin
build=standard
